//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public Nullable<int> OrderByNum { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> CreateUserId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public string DeleteFlag { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public Nullable<int> DeleteUserId { get; set; }
    }
}
